### ISSUE TITLE
 시작부터 않되는데  왜 그럴까요?

### ISSUE THREAD

**Issue by zangzang** [devHudi/gatsby-starter-hoodie#134]
안녕하세요. 
문의 드립니다. 

 시작부터 안되는데  왜 그럴까요?
![image](https://user-images.githubusercontent.com/12781571/208869270-259ac280-b8f2-44a6-ad6f-eade5e810d84.png)

다른분이 만든것도 거의 같은 시점에 오류를 만들어 냅니다.
![image](https://user-images.githubusercontent.com/12781571/208869801-cc0283dc-3b12-4444-9f12-258416d9fd0e.png)

그런데 기본인 npx gatsby new gatsby-starter-blog https://github.com/gatsbyjs/gatsby-starter-blog 로 하면 오류 없이 정상적으로 동작합니다.

npm : 8.19.2
node : v18.12.1

**Comment by devHudi** [comment]
안녕하세요, @zangzang 님. 현재 node v14 버전까지 대응하고 있습니다.
https://github.com/devHudi/gatsby-starter-hoodie/issues/127
해당 이슈 확인해주시면 감사드리겠습니다.
