### ISSUE TITLE
Post List의 frontmatter description이 표기되지 않는 문제

### ISSUE THREAD

**Issue by rxjw95** [devHudi/gatsby-starter-hoodie#136]
frontmatter의 description을 작성해도 포스트 리스트에 표기되지 않고, **본문 요약 내용만 표기되는 문제**가 있는 것 같습니다.

---
title: "blah blah"
description: "해당 속성을 작성하면 포스트 목록에서 title, date 다음으로 이 텍스트가 표기되어야 한다."
date: 2022-06-25
update: 2022-06-25
tags:
  - spring
---

## 문제 해결

pages/index.jsx에서 pageQuery문의 allMarkdownRemark > nodes > frontmatter에 description을 추가해서 post들의 frontmatter 속성중 description을 함께 읽어오면 될 것 같습니다!

이로부터 발생하는 추가적인 이슈는 다음과 같습니다.

- `PostList` 컴포넌트에서는 exceprt 정보만 렌더링합니다. description 존재 여부에 따른 조건부 렌더링이 필요할 것 같습니다.
- 코드 작업 영역이 #120 이슈와 연관되어 있습니다.

도움이 될 것 같은 문서도 올려두겠습니다.
https://www.gatsbyjs.com/plugins/gatsby-transformer-remark/

좋은 블로그 만들어주셔서 감사합니다!

**Comment by devHudi** [comment]
[해당 PR](https://github.com/devHudi/gatsby-starter-hoodie/pull/137)에서 해결되었음
