### ISSUE TITLE
메인에 한국어로 바로 가기에 404 오류가 나고 있습니다.

### ISSUE THREAD

**Issue by ysyang1973** [devHudi/gatsby-starter-hoodie#156]
![image](https://github.com/devHudi/gatsby-starter-hoodie/assets/110577569/8d5a8dd2-eef1-4857-af93-4a09589c506a)
링크가 없거나 문서가 있다면 어딘지 알고 싶습니다.

https://github.com/devHudi/gatsby-starter-hoodie/blob/develop/README-kr.md

**Comment by devHudi** [comment]
https://github.com/devHudi/gatsby-starter-hoodie/blob/main/README-kr.md

한국어 문서 주소입니다. 리드미는 수정해두겠습니다 🙏
