### ISSUE TITLE
폴더를 시리즈로 만드는 기능

### ISSUE THREAD

**Issue by changwoomon** [devHudi/gatsby-starter-hoodie#17]
현재 제 `/contents/posts/` 폴더입니다.

<img src="https://user-images.githubusercontent.com/59998179/126888927-c9ee7746-b777-41e1-9307-86ceb6663c11.png" width=200>

심심풀이로 푸는 백준 풀이를 올리고 있는데, 그렇게 올려버린 파일이 100개가 훨씬 넘네요,,, 저 많은 아이들을 한꺼번에 시리즈로 등록하는 기능이 있으면 좋을 것 같습니다. (+ `/contents/posts/`에 `.md`로 계속 저렇게 글을 올리니 폴더가 좀 어지럽네요...)

**Comment by devHudi** [comment]
포스트의 시리즈는 frontmatter에 명시적으로 기술하는 것이 바람직하다 생각되어 이슈를 닫습니다.
