### ISSUE TITLE
동일 날짜 한정 글 순서에 버그

### ISSUE THREAD

**Issue by changwoomon** [devHudi/gatsby-starter-hoodie#18]
안녕하세요. 동일한 날짜에 한해 글 순서에 버그가 있는 것을 발견했습니다.

<img src="https://user-images.githubusercontent.com/59998179/126889084-7778aafa-0ca2-435e-a47b-6333abfa5a98.png" width=400>

현재 제 블로그 마지막 post인 `[백준] 20164_홀수 홀릭 호석`에 들어가 보겠습니다.

<img src="https://user-images.githubusercontent.com/59998179/126889102-e0134016-9c18-4342-b590-95508e625421.png" width=600>

메인 페이지에서 `[백준] 20164_홀수 홀릭 호석` 밑에 존재하던 post인 `[백준] 20207_달력`이 `Previous Post`에 있어야 하나 실제로 나오는 것은 `[백준] 21608_상어 초등학교`인 버그가 있습니다.

아마 동일한 날짜에 한해서만 이 버그가 발생하는 것 같습니다.

**Comment by devHudi** [comment]
안녕하세요, @changwoomon 님. 
해당 문제는 포스트 Frontmatter 에서 `date` 필드에 시간까지 추가하는 방법으로 해결하실 수 있습니다.
날짜가 동일한 포스트의 경우 시간을 지정해야 의도대로 정렬이 가능합니다. 감사합니다.
