### ISSUE TITLE
TOC 버그

### ISSUE THREAD

**Issue by changwoomon** [devHudi/gatsby-starter-hoodie#19]
<img src="https://user-images.githubusercontent.com/59998179/126889254-da2d2986-ce1e-4cbf-93c2-0627b6c19aa9.png" width=700>
<br><br>

- 상위 항목
  - 하위 항목
<br><br>
- 항목
- 항목
<br><br>
두 경우 모두 항목이 가까이 붙어있을 때 TOC에 클릭하면 올바른 곳으로 가지긴 하는데 검은색 불은 그 아래 항목이 들어옵니다 ㅠㅠ 고쳐주세요

**Comment by devHudi** [comment]
#170 에서 해결되었습니다 🙏

**Comment by changwoomon** [comment]
오예 감사합니당
