### ISSUE TITLE
(੭•̀ᴗ•̀)੭🔥

### ISSUE THREAD

**Issue by changwoomon** [devHudi/gatsby-starter-hoodie#20]
저의 트레이드 마크 이모지의 눈 크기가 다릅니다.

이모지는 다음과 같습니다. (੭•̀ᴗ•̀)੭🔥

블로그에서는 아래처럼 보입니다.

<img src="https://user-images.githubusercontent.com/59998179/126889455-caef37c3-aceb-4444-83fb-a50e38d20033.png" width=500>

자세히 보시면 양쪽 눈의 크기가 다릅니다.

다른 사이트에서는 아래처럼 눈의 크기가 동일하게 나옵니다.

> GitHub

<img src="https://user-images.githubusercontent.com/59998179/126889474-929ecbf3-21ee-4ed0-b96e-9e64963b6d4d.png" width=400>

> Kaggle

<img src="https://user-images.githubusercontent.com/59998179/126889502-9b6f3cf0-e176-4006-9afc-be64cc769359.png" width=200>

고쳐주세요 (੭•̀ᴗ•̀)੭🔥

**Comment by devHudi** [comment]
안녕하세요. @changwoomon  님. 이슈 열어주셔서 감사드립니다.
작성해주신 문제는 Noto Sans 폰트와 관련된 문제로 파악됩니다. 
해결이 필요하시면, Bio 컴포넌트의 코드 일부를 커스텀하시어 스타일을 변경해주시면 될 것 같습니다.
감사합니다.

**Comment by changwoomon** [comment]
> 안녕하세요. @changwoomon 님. 이슈 열어주셔서 감사드립니다.
> 작성해주신 문제는 Noto Sans 폰트와 관련된 문제로 파악됩니다.
> 해결이 필요하시면, Bio 컴포넌트의 코드 일부를 커스텀하시어 스타일을 변경해주시면 될 것 같습니다.
> 감사합니다.

네~! (੭•̀ᴗ•̀)੭🔥
