### ISSUE TITLE
본문 문단 스크롤

### ISSUE THREAD

**Issue by changwoomon** [devHudi/gatsby-starter-hoodie#37]
본문 문단에 스크롤 생김 (웬만한 수식 거의 다)

<img src="https://user-images.githubusercontent.com/59998179/128192850-42fcc946-2eb7-4ea0-81d3-4036131739cf.png" height=600>
<img src="https://user-images.githubusercontent.com/59998179/128192859-285da0f8-1175-4632-a30d-80fb54040b34.png" height=600>
<img src="https://user-images.githubusercontent.com/59998179/128192866-353f7617-dc38-4e6f-8821-4fe420073fbc.png" height=600>

**Comment by devHudi** [comment]
Solved
