### ISSUE TITLE
Found bug about Markdown list(-)

### ISSUE THREAD

**Issue by changwoomon** [devHudi/gatsby-starter-hoodie#5]
Hi Hudi, I found a bug when I was writing.
Markdown written is as follows.

<img src="https://user-images.githubusercontent.com/59998179/124382530-e402e480-dd02-11eb-9f9a-e53e9e94378a.png">
<br><br>

If you look at this in VS Code preview, it looks like the picture below and I wanted it to look like this.

<img src="https://user-images.githubusercontent.com/59998179/124382565-114f9280-dd03-11eb-8424-6ed28cd41389.png" width=800>
<br><br>

But what's written on the actual blog is as shown in the picture below.

<img src="https://user-images.githubusercontent.com/59998179/124382578-27f5e980-dd03-11eb-932f-73a5d35c420f.png" height=500>
<br><br>

Is it because the tag <img> is right under the line where the list('-') came out? It does not apply properly.

Can you fix it for me? If this isn't a bug, tell me how to write it correctly!

**Comment by devHudi** [comment]
Thanks for opening the issue. This issue was resolved in PR #6.
