### ISSUE TITLE
모바일 사파리 네비게이션 아이콘 위치 이슈

### ISSUE THREAD

**Issue by devHudi** [devHudi/gatsby-starter-hoodie#81]
![image](https://user-images.githubusercontent.com/11745691/142226795-9210ada4-9327-491f-bbde-86427fe5d652.png)

**Comment by changwoomon** [comment]
달이 하늘로 승천해요

**Comment by changwoomon** [comment]
![image](https://user-images.githubusercontent.com/59998179/142227154-7472a476-83a1-41d7-8341-c9a28c3d73e7.png)

해도 하늘로 승천해요
