### ISSUE TITLE
JavaScript to TypeScript Migration

### ISSUE THREAD

**Issue by gmkseta** [devHudi/gatsby-starter-hoodie#82]
안녕하세요. 블로그 글 잘 봤습니다.

여러 gatsby starter kit을 찾아봤는데 @devHudi 님이 만드신 이 레포가 제일 깔끔하고 필요한 것만 들어있는 것 같습니다.

좋은 레포 만들어 주셔서 감사합니다.

혹시 Typescript 사용할 계획이 있는지 궁금합니다.

감사합니다.

**Comment by devHudi** [comment]
안녕하세요 @gmkseta 님! 일단 좋은 말씀해주셔서 먼저 감사 말씀 드립니다.

당장 Typescript 를 도입할 계획은 없습니다. 다만, 여유가 될 때마다 점진적으로 TS를 도입하는게 목표입니다.

**Comment by devHudi** [comment]
이슈 닫겠습니다 :)
